repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0  # (Note: v6.0.0 doesn't exist yet, v5.0.0 is likely what you want)
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
